# Generated by Django 5.2.5 on 2025-11-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_threadcategory_remove_post_primary_region_thread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='threadsubcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
