# Generated by Django 5.2.5 on 2026-01-22 16:59

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_threadcategory_slug_and_more'),
    ]

    operations = [
        UnaccentExtension(),
    ]
