# Generated by Django 5.2.5 on 2026-02-04 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_onetimepassword_attempts_onetimepassword_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('stale', 'Stale'), ('ready', 'Ready'), ('failed', 'Failed')], default='stale', max_length=10)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='users.post')),
            ],
        ),
    ]
