# Generated by Django 5.2.5 on 2026-02-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_postsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Recommendation Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PostRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('google_maps_url', models.URLField(blank=True, default='', max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=0, help_text='Rating from 1-5, 0 means no rating')),
                ('price_level', models.CharField(blank=True, choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], default='', max_length=4)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.post')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='users.recommendationcategory')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
