# Generated by Django 5.2.5 on 2026-02-24 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_recommendationcategory_postrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('content_type', models.CharField(choices=[('post', 'Post'), ('thread', 'Thread')], max_length=10)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='users.post')),
                ('thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='users.thread')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('content_type', 'post'), ('post__isnull', False), ('thread__isnull', True)), models.Q(('content_type', 'thread'), ('post__isnull', True), ('thread__isnull', False)), _connector='OR'), name='sharelink_content_integrity')],
            },
        ),
    ]
