"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from os import access
from pathlib import Path
import environ
from datetime import timedelta

env = environ.Env(
    # set casting, default values
    DEBUG = (bool, False)
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'users', 
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_countries',
    'cities_light',
    'storages',
]

CITIES_LIGHT_INCLUDE_COUNTRIES = ['EC', 'MX','BR', 'US', 'TR']
CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en', 'es', 'abbr']  
CITIES_LIGHT_INCLUDE_CITY_TYPES = ['PPL', 'PPLA', 'PPLA2', 'PPLC',]
# PPL = Populated place (city, town, village);
# PPLA helps with cases like Us > Texas > Austin. It guarantees we get cities that are admin capitals 
# PPLA2 = In Ecuador, this gives us provincial capitals like Cuenca, Loja, etc.
# PPLC = Capital of a political entity (country, state, province, etc.)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # React frontend
    "http://localhost:5173", # Vite frontend
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000", # React frontend
    "http://localhost:5173", # Vite frontend
]

CORS_ALLOW_CREDENTIALS = True

#### BUCKET STORAGE SETTINGS ####
AWS_STORAGE_BUCKET_NAME = env('DO_STORAGE_BUCKET_NAME')
AWS_ACCESS_KEY_ID = env('SPACES_KEY')
AWS_SECRET_ACCESS_KEY = env('SPACES_SECRET')

#API endpoint for uploads
AWS_S3_ENDPOINT_URL = env('DO_ENDPOINT_URL')
AWS_S3_REGION_NAME = env('DO_SPACES_REGION')  # DigitalOcean Spaces region

# CDN Hostname for serving files in the browser
AWS_S3_CDN_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.cdn.digitaloceanspaces.com'

#AWS_DEFAULT_ACL = None
#AWS_QUERYSTRING_AUTH = False  # Get public URLs without query params

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

STATIC_URL = f"https://{AWS_S3_CDN_DOMAIN}/static/"
MEDIA_URL  = f"https://{AWS_S3_CDN_DOMAIN}/media/"

STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directory to collect static files


# Django 4.2+ static and media files settings with DigitalOcean Spaces
### Media files settings (custom storage backends)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "location": "media",
            "default_acl": "public-read",
            "querystring_auth": False,
            "custom_domain": AWS_S3_CDN_DOMAIN,
            "file_overwrite": False,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "location": "static",
            "default_acl": "public-read",
            "querystring_auth": False,
            "custom_domain": AWS_S3_CDN_DOMAIN,
            "file_overwrite": True,
        },
    },
}

#MEDIA_URL = '/media/'
#MEDIA_ROOT = BASE_DIR / 'media' # Directory to store uploaded media files


# CSRF settings for API
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for SPA
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax' # Whether the cookie should be sent with cross-site requests (Lax, Strict, None)
CSRF_USE_SESSIONS = False
CSRF_COOKIE_DOMAIN = None

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'travel-app-db',
        'USER': 'postgres',
        'PASSWORD': '032004',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',), # The type of the auth header
    'AUTH_COOKIE': 'access_token', # Cookie name. Enables cookies if value is set.
    'AUTH_COOKIE_REFRESH': 'refresh_token', # The refresh token cookie name.
    'AUTH_COOKIE_SECURE': False,  # Set to True in production with HTTPS
    'AUTH_COOKIE_HTTP_ONLY': True, # HTTP only cookies are not accessible to JavaScript. 
    'AUTH_COOKIE_SAMESITE': 'Lax', # Lax is the default and allows the cookie to be sent with cross-site requests.
    'AUTH_COOKIE_PATH': '/', # The path of the auth cookie
    'AUTH_COOKIE_DOMAIN': None, # A specific domain to set the cookie on (None means any domain)
}

# REST Framework settings for JWT authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',  # Custom JWT auth that reads from cookies
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # Allow any user to access the API 
    ),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

# Looking to send emails in production? Check out our Email API/SMTP product!
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = '2525'
EMAIL_USE_TLS = True # Enable TLS for secure email sending

# Mailtrap Email API settings
EMAIL_BACKEND_MODE = env('EMAIL_BACKEND_MODE')
MAILTRAP_API_TOKEN = env('MAILTRAP_API_TOKEN')
MAILTRAP_FROM_EMAIL = env('MAILTRAP_FROM_EMAIL')
MAILTRAP_FROM_NAME = env('MAILTRAP_FROM_NAME')
MAILTRAP_API_URL = env('MAILTRAP_API_URL')
FRONTEND_URL = env('FRONTEND_URL')

GOOGLE_CLIENT_ID = env('CLIENT_ID')
GOOGLE_CLIENT_SECRET = env('CLIENT_SECRET')
SOCIAL_AUTH_PASSWORD = env('SOCIAL_AUTH_PASSWORD')

GEMINI_API_KEY = env('GEMINI_API_KEY')
GEMINI_MODEL = env("GEMINI_MODEL")
GEMINI_FALLBACK_MODELS = env.list("GEMINI_FALLBACK_MODELS")
GEMINI_SUMMARY_MAX_OUTPUT_TOKENS = env.int('GEMINI_SUMMARY_MAX_OUTPUT_TOKENS')
