import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useState, useCallback, useRef } from "react";
import { getPostSchema, transformPostData } from './validationSchema';
import LocationSelector from './LocationSelector';
import RecommendationForm from './RecommendationForm';
import postService from '../../services/postService';
import BlockEditor from './BlogEditor/BlockEditor';
import { toast } from 'sonner';

/*
UseCallback is used to memoize the handlers for country and city changes.
*/

const Form = ({ onSuccess, initialData = null, isEditing = false, showTitle = true }) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState('');
  const [contentError, setContentError] = useState('');
  const editorRef = useRef(null); // Ref to access editor methods 
  const recommendationRef = useRef(null);
  const [showRecommendations, setShowRecommendations] = useState(
    initialData?.recommendations?.length > 0 || false
  );

  const schema = getPostSchema();

  const {
    register,
    handleSubmit,
    formState: { errors, isValid },
    watch,
    setValue,
    reset,
    clearErrors,
    setError
  } = useForm({
    resolver: zodResolver(schema),
    mode: 'onChange', // Validate on change 
    defaultValues: {
      title: initialData?.title || '',
      content: initialData?.content || '', // Will store JSON string generated by Editor.js
      location_scope: initialData?.location_scope || 'none',
      primary_country: initialData?.primary_country || '',
      primary_city: initialData?.primary_city || '',
      status: initialData?.status || 'draft'
    }
  });

  // Watch for location scope changes
  const locationScope = watch('location_scope');
  const selectedCountry = watch('primary_country');
  const selectedCity = watch('primary_city');

  // Handle country selection with proper cleanup
  const handleCountryChange = useCallback((countryCode) => {
    setValue('primary_country', countryCode, { shouldValidate: true });
    // Clear city when country changes
    if (locationScope === 'city' && selectedCity) {
      setValue('primary_city', '', { shouldValidate: true });
    }
    // Clear country errors when user selects
    if (countryCode) {
      clearErrors('primary_country');
    }
  }, [setValue, locationScope, selectedCity, clearErrors]);

  // Handle city selection
  const handleCityChange = useCallback((cityId) => {
    setValue('primary_city', cityId, { shouldValidate: true });
    // Clear city errors when user selects
    if (cityId) {
      clearErrors('primary_city');
    }
  }, [setValue, clearErrors]);

  // Handle editor content change
  const handleEditorChange = useCallback((editorData) => {
    // Check if editor has content
    const hasContent = editorData?.blocks?.some(block => {
      if (block.type === 'paragraph' || block.type === 'header') {
        return block.data?.text?.trim().length > 0;
      }
      if (block.type === 'image') {
        return block.data?.file?.url; // Image URL
      }
      if (block.type === 'list') {
        return block.data?.items?.length > 0; 
      }
      return false;
    });

    if (hasContent) {
      // Store as JSON string in the content field
      setValue('content', JSON.stringify(editorData), { shouldValidate: true }); 
      setContentError('');
      clearErrors('content');
    } else {
      setValue('content', '', { shouldValidate: true });
    }
  }, [setValue, clearErrors]);

  // Form submission with proper error handling
  const onSubmit = async (formData) => {
    // Get editor content before submit
    if (editorRef.current) {
      const editorData = await editorRef.current.save();
      
      if (!editorData || editorData.blocks.length === 0) {
        setContentError('Content is required');
        return;
      }

      formData.content = JSON.stringify(editorData);
    }

    setIsSubmitting(true);
    setSubmitError('');

    try {
      // Transform data before sending to backend
      const transformedData = transformPostData(formData);

      let result;
      if (isEditing && initialData) {
        result = await postService.updatePost(
          initialData.author_username,
          initialData.slug,
          transformedData
        );
      } else {
        result = await postService.createPost(transformedData);
      }

      if (result.success) {
        const savedPost = result.data;

        // Handle recommendations
        if (showRecommendations && recommendationRef.current?.hasData()) {
          const recsData = recommendationRef.current.getData();

          // If editing, delete existing recommendations first
          if (isEditing && initialData?.recommendations?.length > 0) {
            for (const existing of initialData.recommendations) {
              await postService.deleteRecommendation(existing.id);
            }
          }

          // Bulk create the new recommendations if there are any recommendations to add
          if (recsData.length > 0) {
            const cleanedRecs = recsData.map(({ _tempId, id, created_at, updated_at, post, category_name, category_slug, ...rest }) => rest);
            const recResult = await postService.bulkCreateRecommendations(savedPost.id, cleanedRecs);
            if (!recResult.success) {
              toast.warning('Post saved, but some recommendations failed to save.');
            }
          }
        } else if (isEditing && !showRecommendations && initialData?.recommendations?.length > 0) {
          // Toggle turned off during edit -- delete all existing recommendations
          for (const existing of initialData.recommendations) {
            await postService.deleteRecommendation(existing.id);
          }
        }

        if (onSuccess) {
          onSuccess(savedPost);
        }
        if (!isEditing) {
          reset();
          // Clear editor
          if (editorRef.current) {
            editorRef.current.clear();
          }
          if (recommendationRef.current) {
            recommendationRef.current.clear();
          }
          setShowRecommendations(false);
        }
      } else {
        // Handle backend validation errors
        if (result.error && typeof result.error === 'object') {
          // Map backend errors to form fields
          Object.keys(result.error).forEach(field => {
            if (field in formData) {
              setError(field, {
                type: 'server',
                message: Array.isArray(result.error[field])
                  ? result.error[field][0]
                  : result.error[field]
              });
            }
          });
        } else {
          setSubmitError(result.error || 'Failed to save post');
        }
      }
    } catch (error) {
      console.error('Form submission error:', error);
      setSubmitError('Network error. Please check your connection and try again.');
    } finally {
      setIsSubmitting(false);
    }
  };

  // Handle form reset
  const handleReset = useCallback(() => {
    reset();
    setSubmitError('');
    setContentError('');
    clearErrors();
    // Clear editor
    if (editorRef.current) {
      editorRef.current.clear();
    }
    // Clear recommendations
    if (recommendationRef.current) {
      recommendationRef.current.clear();
    }
    setShowRecommendations(false);
  }, [reset, clearErrors]);

  // Parse initial content for editor (if editing)
  const getInitialEditorData = () => {
    if (initialData?.content) {
      try {
        return JSON.parse(initialData.content);
      } catch {
        // If content is plain text (old format), convert to editor format
        return {
          blocks: [{
            type: 'paragraph',
            data: { text: initialData.content }
          }]
        };
      }
    }
    return null;
  };

  return (
    <div className="max-w-2xl mx-auto p-6">
      {showTitle && (
        <h2 className="text-2xl font-bold mb-6 font-editorial text-[var(--text-color-ink)]">
          {isEditing ? 'Edit Post' : 'Create New Post'}
        </h2>
      )}

      {submitError && (
        <div className="mb-4 p-4 bg-red-100 border border-red-400 text-red-700 rounded-md">
          {submitError}
        </div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Title Field */}
        <div>
          <label htmlFor="title" className="block text-sm font-medium text-[var(--text-color-ink)] mb-1">
            Title *
          </label>
          <input
            type="text"
            id="title"
            {...register('title')}
            className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-[var(--primary-color-royal)] ${
              errors.title ? 'border-red-500' : 'border-[var(--border-color-line)]'
            }`}
            placeholder="Enter post title..."
          />
          {errors.title && (
            <p className="mt-1 text-sm text-red-600">{errors.title.message}</p>
          )}
        </div>

        {/* Location Scope */}
        <div>
          <label htmlFor="location_scope" className="block text-sm font-medium text-[var(--text-color-ink)] mb-1">
            Location Scope *
          </label>
          <select
            id="location_scope"
            {...register('location_scope')}
            className="w-full px-3 py-2 border border-[var(--border-color-line)] rounded-md focus:outline-none focus:ring-2 focus:ring-[var(--primary-color-royal)]"
          >
            <option value="none">Not location specific</option>
            <option value="country">Country specific</option>
            <option value="city">City specific</option>
          </select>
          {errors.location_scope && (
            <p className="mt-1 text-sm text-red-600">{errors.location_scope.message}</p>
          )}
        </div>

        {/* Location Selector Component */}
        <LocationSelector
          locationScope={locationScope}
          selectedCountry={selectedCountry}
          selectedCity={selectedCity}
          onCountryChange={handleCountryChange}
          onCityChange={handleCityChange}
          errors={errors}
        />

        {/* Status Field */}
        <div>
          <label htmlFor="status" className="block text-sm font-medium text-[var(--text-color-ink)] mb-1">
            Status *
          </label>
          <select
            id="status"
            {...register('status')}
            className="w-full px-3 py-2 border border-[var(--border-color-line)] rounded-md focus:outline-none focus:ring-2 focus:ring-[var(--primary-color-royal)]"
          >
            <option value="draft">Draft</option>
            <option value="published">Published</option>
          </select>
          {errors.status && (
            <p className="mt-1 text-sm text-red-600">{errors.status.message}</p>
          )}
        </div>

        {/* Content Field (Now with Editor.js) */}
        <div>
          <label className="block text-sm font-medium text-[var(--text-color-ink)] mb-1">
            Content *
          </label>
          <BlockEditor
            ref={editorRef}
            initialData={getInitialEditorData()}
            onChange={handleEditorChange}
            placeholder="Start writing your story..."
            minHeight="300px"
          />
          {(errors.content || contentError) && (
            <p className="mt-1 text-sm text-red-600">
              {errors.content?.message || contentError}
            </p>
          )}
        </div>

        {/* Recommendations Toggle */}
        <div className="border-t border-[var(--border-color-line)] pt-6">
          <div className="flex items-center justify-between mb-4">
            <div>
              <label className="text-sm font-medium text-[var(--text-color-ink)]">
                Recommendations
              </label>
              <p className="text-xs text-[var(--text-color-ink-400)] mt-1">
                Add places, services, or activities you would like to recommend
              </p>
            </div>
            <button
              type="button"
              onClick={() => setShowRecommendations(!showRecommendations)}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                showRecommendations ? 'bg-[var(--primary-color-royal)]' : 'bg-gray-300'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  showRecommendations ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>

          {showRecommendations && (
            <RecommendationForm
              ref={recommendationRef}
              initialRecommendations={initialData?.recommendations || []}
            />
          )}
        </div>

        {/* Submit Buttons */}
        <div className="flex justify-end space-x-4">
          <button
            type="button"
            onClick={handleReset}
            className="px-4 py-2 text-[var(--text-color-ink)] bg-[var(--color-background-snow)] rounded-md hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-gray-500 transition-colors"
            disabled={isSubmitting}
          >
            Reset
          </button>
          <button
            type="submit"
            disabled={isSubmitting}
            className="px-6 py-2 bg-[var(--primary-color-royal)] text-white rounded-md hover:bg-[var(--primary-color-royal-600)] focus:outline-none focus:ring-2 focus:ring-[var(--primary-color-royal)] disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {isSubmitting 
              ? (isEditing ? 'Updating...' : 'Creating...') 
              : (isEditing ? 'Update Post' : 'Create Post')
            }
          </button>
        </div>
      </form>
    </div>
  );
};

export default Form;
